### ISSUE TITLE
Support FMOD Live Update

### ISSUE THREAD

**Issue by GitGhillie** [Salzian/bevy_fmod#14]

**Comment by Salzian** [comment]
Feel like this is a big one? We may have to consider this functionality in all components. Do you already tried something out in regards to this?

**Comment by GitGhillie** [comment]
Surprisingly all it takes is to set the flag [FMOD_STUDIO_INIT_LIVEUPDATE](https://www.fmod.com/docs/2.01/studio/editing-during-live-update.html). Only thing is we probably want this behind a feature flag as we don't want to surprise users with an audio crate that opens up a (local) connection by default. Feel free to pick this one up btw

**Comment by Salzian** [comment]
If it's that easy... But makes sense, as most of the necessary logic may already be included in the fmod libs. I'll give it a try.
