### ISSUE TITLE
Diagnostics

### ISSUE THREAD

**Issue by GitGhillie** [Salzian/bevy_fmod#15]
FMOD (Studio) API provides a lot of functionality for diagnostics like CPU usage, memory usage, etc.
Maybe we can start thinking about how we can nicely integrate this and use this issue as a tracker.

**Comment by GitGhillie** [comment]
Interesting to note that FMOD Studio has a profiler built-in, which can display audio related diagnostics while you are running the game (like audio CPU usage, instances, memory usage). Therefore I think this issue is pretty low priority or maybe we can even close it if there is nothing we can do which the profiler can't.

**Comment by Salzian** [comment]
Let's close it for now. If the need arises for something more specific, we can open a new issue.
