### ISSUE TITLE
Spatial audio breaks when adding RapierPhysicsPlugin

### ISSUE THREAD

**Issue by GitGhillie** [Salzian/bevy_fmod#54]
When adding `RapierPhysicsPlugin` from bevy_rapier3d to the spatial example you will get compilation errors saying `Velocity is ambiguous`. But in my own project I've also had a case where it silently broke the spatial audio (resulting in just 2d audio).

I think it would be a good time to also think about the following question: Would it be beneficial if a physics engine can provide the velocity instead?
1. Avoids redundant calculation of velocity, physics engines will calculate this anyway.
2. More accurate velocity if it's calculated by a physics engine?
3. Avoids worry about ambiguous imports.

Let's also include bevy_xpbd when we come to a solution.

**Comment by Salzian** [comment]
So we either need to support a bunch of popular physics libraries or add some sort of adapter layer that can be extended by other crates. Like exposing a trait that can be used to build adapter crates like `bevy_fmod_rapier`.

**Comment by GitGhillie** [comment]
Maybe for now we can keep doing our own velocity calculation and find a solution to this bug so we don't have to worry about physics libraries. I don't think there will be much advantage by letting a physics engine calculate the velocity. What do you think?

**Comment by GitGhillie** [comment]
https://github.com/Salzian/bevy_fmod/pull/56 solved this for me in the sense that it's not necessary anymore to import Velocity directly.

**Comment by GitGhillie** [comment]
Closing for now; if it's still interesting maybe we can create a new issue for the idea of being able to use the velocity as provided by a physics engine
