### ISSUE TITLE
Ability for one off spatial sounds

### ISSUE THREAD

**Issue by BrianWiz** [Salzian/bevy_fmod#72]
It would be nice to play a spatial sound from any location without necessarily having to attach it to an entity.

So for example, I have a shotgun with some reverb, I want it playing from the location of the shot, not attached to the weapon entity, because I don't want the sound following the weapon around (my game is fast, you'd notice it).

It seems that right now I would have to create an entity, attach a `SpatialAudioBundle` to it, track it's playback state, then delete the entity.

**Comment by GitGhillie** [comment]
The velocity of the sound would always be 0 in such cases right? If that's the case I think there is a nice way to do this

**Comment by BrianWiz** [comment]
@GitGhillie that is correct yep

**Comment by GitGhillie** [comment]
Made a PR if you want to give your thoughts on it ^
