### ISSUE TITLE
Consider disambiguating names with Bevy's prelude

### ISSUE THREAD

**Issue by msvbg** [Salzian/bevy_fmod#85]
It seems that `AudioSource` conflicts with a definition in the bevy prelude. Even if I disable bevy_audio, rust analyzer seems to get tripped up by this. The examples import both `*` and `AudioSource` from the bevy_fmod prelude, which looks a little bit weird to my eyes. I think naming it something like `FmodAudioSource` would be a little bit cleaner and avoid these problems.

**Comment by msvbg** [comment]
I don't see preludes that way. My game is now ~12k SLOC and most files start with `use bevy::prelude::*`, and I think it is common practice to use the bevy prelude in the ecosystem. It might be better for the library to not have a prelude at all if it is not intended to be used.

**Comment by Peepo-Juice** [comment]
I am with @Salzian on this one. That's not to say that this complaint is invalid, but the best solution is to use aliases, and not to use preludes and wildcards. 

Even if we did use the FmodXxx naming scheme, whats there to say it wont conflict with bevy or some other crate in the future? I'm not saying its likely they will implement their own fmod integration but its still technically possible. My point is that this solution soils the names for our crate and everyone else who chooses to take this path without actually eliminating the issue, whereas the solutions outlined by @Salzian allows for each crate to name their structs however they want while actually solving it once and for all. Its probably why Rust added aliasing in the first place.

**Comment by GitGhillie** [comment]
> Even if I disable bevy_audio, rust analyzer seems to get tripped up by this. 

IMO this is an issue with Bevy/RA. If the bevy_audio feature is disabled then the Bevy audio types shouldn't be compiled

**Comment by GitGhillie** [comment]
> IMO this is an issue with Bevy/RA. If the bevy_audio feature is disabled then the Bevy audio types shouldn't be compiled

Nvm this actually. Because we implement AudioSinkPlayback we depend on bevy_audio. Though it wouldn't be too difficult to get rid of that dependency if we want to go that route.

**Comment by Salzian** [comment]
@GitGhillie Didn't see your comment and just got to the same conclusion. I opened a PR. That will not solve all questions asked in this PR, but will resolve the root problem of the name clash.

**Comment by msvbg** [comment]
Nice. This is satisfactory to me.
