### ISSUE TITLE
Using bevy_fmod requires adding libfmod as dependency as well

### ISSUE THREAD

**Issue by GitGhillie** [Salzian/bevy_fmod#91]
Since #73 it seems to be necessary for users to add libfmod to their cargo.toml next to bevy_fmod.
This is because of the usage of `libfmod::StopMode` which the user must set when constructing the `AudioSource`.
https://github.com/Salzian/bevy_fmod/pull/73/files#diff-a0d564d99c2bcbac0bf318444c9701005d0ff57d990104e268e523df94b393bcR37

I don't think this is intended (otherwise the Usage guide in the readme needs to be adjusted as well), so I think we should re-export the type/libfmod or newtype it.

One thing I don't understand yet, is why do the examples compile even though libfmod is not part of the dev dependencies?

**Comment by Salzian** [comment]
I pushed a commit that makes the StopMode `pub use`. Can you check if that was sufficient?

https://github.com/Salzian/bevy_fmod/commit/6f0d5a440be540f6529ce93b11b87682a63e8f9b

**Comment by GitGhillie** [comment]
That didn't do the trick, here is what I have in mind: https://github.com/Salzian/bevy_fmod/pull/92

**Comment by GitGhillie** [comment]
Fixed by 92
